In [1]:
import numpy as np

In [27]:
p1 = np.array([3, 2, 1]).reshape((3,1))
p2 = np.array([2, 3, 1]).reshape((3,1))

In [28]:
m1 = p1 < p1.T
m2 = p2 < p2.T

In [29]:
m1

array([[False, False, False],
       [ True, False, False],
       [ True,  True, False]])

In [30]:
m2

array([[False,  True, False],
       [False, False, False],
       [ True,  True, False]])

In [32]:
pmatrix = np.stack([m1, m2])

In [33]:
wcet = np.array([0.5, 0.5, 3]).reshape((3,1))

In [35]:
result = pmatrix @ wcet

In [36]:
result.shape

(2, 3, 1)

In [40]:
result

array([[[0. ],
        [0.5],
        [1. ]],

       [[0.5],
        [0. ],
        [1. ]]])

In [53]:
result.ravel(order="F").reshape((3,2))

array([[0. , 0.5],
       [0.5, 0. ],
       [1. , 1. ]])

# Several priorities input

In [107]:
p = np.array([[3, 2], [2, 3], [1, 1]])

In [108]:
p

array([[3, 2],
       [2, 3],
       [1, 1]])

In [109]:
p.ravel(order='F').reshape(2, 3, 1)

array([[[3],
        [2],
        [1]],

       [[2],
        [3],
        [1]]])

In [110]:
x = p.ravel(order='F').reshape(2, 3, 1)
x < x.T

array([[[False, False],
        [False,  True],
        [False, False]],

       [[ True, False],
        [False, False],
        [False, False]]])

In [111]:
x

array([[[3],
        [2],
        [1]],

       [[2],
        [3],
        [1]]])

In [114]:
pm = x < x.transpose((0,2,1))

In [115]:
pm

array([[[False, False, False],
        [ True, False, False],
        [ True,  True, False]],

       [[False,  True, False],
        [False, False, False],
        [ True,  True, False]]])

In [116]:
periods = np.array([2, 3, 6])

In [117]:
pm / periods

array([[[0.        , 0.        , 0.        ],
        [0.5       , 0.        , 0.        ],
        [0.5       , 0.33333333, 0.        ]],

       [[0.        , 0.33333333, 0.        ],
        [0.        , 0.        , 0.        ],
        [0.5       , 0.33333333, 0.        ]]])

In [118]:
r = np.array([2, 3, 4]).reshape((3,1))

In [119]:
r

array([[2],
       [3],
       [4]])

In [120]:
r * (pm/periods)

array([[[0.        , 0.        , 0.        ],
        [1.5       , 0.        , 0.        ],
        [2.        , 1.33333333, 0.        ]],

       [[0.        , 0.66666667, 0.        ],
        [0.        , 0.        , 0.        ],
        [2.        , 1.33333333, 0.        ]]])

In [121]:
np.ceil(r * (pm/periods))

array([[[0., 0., 0.],
        [2., 0., 0.],
        [2., 2., 0.]],

       [[0., 1., 0.],
        [0., 0., 0.],
        [2., 2., 0.]]])

In [122]:
wcets = np.array([0.5, 0.5, 3]).reshape(3,1)

In [123]:
np.ceil(r * (pm/periods)) @ wcets

array([[[0. ],
        [1. ],
        [2. ]],

       [[0.5],
        [0. ],
        [2. ]]])