In [1]:
import numpy as np

In [2]:
p = np.array([[3, 2, 1]])

In [3]:
p

array([[3, 2, 1]])

In [4]:
vo = np.ones((3,1))

In [5]:
vo @ p

array([[3., 2., 1.],
       [3., 2., 1.],
       [3., 2., 1.]])

In [6]:
pm = vo @ p

In [9]:
pm > pm.transpose()

array([[False, False, False],
       [ True, False, False],
       [ True,  True, False]])

In [10]:
x = pm > pm.transpose()

In [11]:
x

array([[False, False, False],
       [ True, False, False],
       [ True,  True, False]])

In [12]:
periods = np.array([[2, 3, 6]])

In [13]:
periods

array([[2, 3, 6]])

In [14]:
periods @ x

array([[9, 6, 0]])

In [15]:
periods

array([[2, 3, 6]])

In [16]:
x

array([[False, False, False],
       [ True, False, False],
       [ True,  True, False]])

In [17]:
x.dtype

dtype('bool')

In [18]:
p

array([[3, 2, 1]])

In [21]:
p>p.transpose()

array([[False, False, False],
       [ True, False, False],
       [ True,  True, False]])

In [22]:
t = np.array([[2, 3, 6]]).transpose()

In [23]:
t

array([[2],
       [3],
       [6]])

In [27]:
(p>p.transpose()) / t.transpose()

array([[0.        , 0.        , 0.        ],
       [0.5       , 0.        , 0.        ],
       [0.5       , 0.33333333, 0.        ]])

In [28]:
p

array([[3, 2, 1]])